### ISSUE TITLE
score your item visibility in overview canvas

### ISSUE THREAD

**Issue by RobRomgens** [WardMe/storymapper-widget#5]
Nice widget. I would like to see something more with "score your item". Now I can fill it in, but in the canvas I only see the heart emoticon (no number, and no further details) , which makes it not handy if I show my journey to others.

**Comment by WardMe** [comment]
There seems to be a bug, it should show the number next to the heart:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/3016302/161279781-3ac127f2-1f89-4082-9668-b5666977da4d.png">

I'll try to push an update soon.

**Comment by WardMe** [comment]
New update pushed:
![image](https://user-images.githubusercontent.com/3016302/161374562-390fd936-40ea-46da-a6b2-3a47b6df6b36.png)

**Comment by RobRomgens** [comment]
Waaw looks good!
Will the updated be pushed automatically into my widget?

**Comment by WardMe** [comment]
You'll have to manually update it to the latest version:
- Right click the widget
- Select the "Widgets" menu
- Select "Update to latest version"


https://user-images.githubusercontent.com/3016302/161393030-61353692-9121-41d1-89e5-e2aeb3d8c35c.mov

**Comment by RobRomgens** [comment]
Works perfect!
