### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by RobRomgens** [WardMe/storymapper-widget#8]
Hi there, 
Still very happy with your widget! I just promoted it to all my colleagues. 

Idea 1) is it possible to show the description in de card (in small font), so that we can see the info without clicking on a card
Idea 2) we now have choice in several icons/colors, but could you add one with 'other' or 'else' or something else....?

thanks :)

**Comment by WardMe** [comment]
Great idea, I've pushed an update with the "Other" option and you can now show and hide the description.
